name: My Solar System

on:
  workflow_dispatch:
  push:
    branches: [ "feature" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout action
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # - run: npm ci
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
